language: python

python:
  - "2.7"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - python-numpy
    - gfortran

install:
  - travis_wait 20 make build

script:
  - make test

after_success:  
  - make coveralls

notifications:
  email: false
